- name: Create EC2 Instances and R53 using Ansible Playbook
  hosts: localhost
  vars:
    zone: surya-devops.online
    instances:
    - db
    - backend
    - frontend
  tasks:
    - name: create EC2 instances
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        name: "{{item}}"
        security_group: Frontend-Security-Group
        image_id: ami-090252cbe067a9e58
        tags:
          Name: "{{item}}"
      loop: "{{instances}}"
      register: ec2_info

    - name: print output
      ansible.builtin.debug:
        msg: "Output: {{ec2_info}}"

    - name: create r53 records
      community.aws.route53:
        state: present
        zone: "{{zone}}"
        record: "{{item}}.{{zone}}"
        type: A
        value: 
        - 172.31.43.37
        - 172.31.44.59
        - 54.83.73.180
        overwrite: true
        ttl: 10
      loop:
      - "{{instances}}"
