- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start mysqld service
  ansible.builtin.service:
    name: mysqld
    enabled: true
    state: started

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9


- name: check DB root password created or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    filter: version
    login_host: "{{login_host}}"
  ignore_errors: true
  register: mysql_connection_output

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{ mysql_connection_output }}"

- name: setup DB password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
  when: mysql_connection_output.failed is true